@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 20 16:48:50 +0800 2022
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim MiniMIPS32_SYS_tb_behav -key {Behavioral:sim_1:Functional:MiniMIPS32_SYS_tb} -tclbatch MiniMIPS32_SYS_tb.tcl -view d:/Downloads/coalab-master/CPU_core/MiniMIPS32.sim/sim_1/behav/MiniMIPS32_SYS_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
