# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/data/func_test/soc_sram_func/run_vivado/soc_lite.xdc

# IP: ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] -quiet
