# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.cache/wt [current_project]
set_property parent.project_path D:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/data/func_test/soft_func/func/obj/inst_ram.coe
add_files D:/data/func_test/soft_func/func/obj/data_ram.coe
add_files D:/data/func_test/soft_c/build/add_inst.coe
add_files D:/data/func_test/soft_c/build/add_data.coe
add_files d:/data/func_test/soft_c/build/fib_inst.coe
add_files d:/data/func_test/soft_c/build/fib_data.coe
add_files d:/data/func_test/soft_c/build/leap-year_inst.coe
add_files d:/data/func_test/soft_c/build/leap-year_data.coe
add_files d:/data/func_test/soft_c/build/prime_inst.coe
add_files d:/data/func_test/soft_c/build/prime_data.coe
add_files d:/data/func_test/soft_c/build/quick-sort_inst.coe
add_files d:/data/func_test/soft_c/build/quick-sort_data.coe
add_files d:/data/func_test/soft_c/build/bin-search_inst.coe
add_files d:/data/func_test/soft_c/build/bin-search_data.coe
add_files d:/data/func_test/soft_c/build/matrix_inst.coe
add_files d:/data/func_test/soft_c/build/matrix_data.coe
add_files d:/data/func_test/soft_c/build/shuixianhua_inst.coe
add_files d:/data/func_test/soft_c/build/shuixianhua_data.coe
read_verilog -library xil_defaultlib {
  D:/data/func_test/soc_sram_func/rtl/myCPU/defines.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/MiniMIPS32.v
  D:/data/func_test/soc_sram_func/rtl/BRIDGE/bridge_1x2.v
  D:/data/func_test/soc_sram_func/rtl/CONFREG/confreg.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/cp0_reg.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/exe_stage.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/exemem_reg.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/hilo.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/id_stage.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/idexe_reg.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/if_stage.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/ifid_reg.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/mem_stage.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/memwb_reg.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/mycpu.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/regfile.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/scu.v
  D:/data/func_test/soc_sram_func/rtl/myCPU/wb_stage.v
  D:/data/func_test/soc_sram_func/rtl/soc_lite_top.v
}
read_ip -quiet D:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all d:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all d:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all d:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/clk_pll/clk_pll_ooc.xdc]

read_ip -quiet D:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/inst_ram/inst_ram.xci
set_property used_in_implementation false [get_files -all d:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/inst_ram/inst_ram_ooc.xdc]

read_ip -quiet D:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all d:/data/func_test/soc_sram_func/run_vivado/mycpu_prj1/mycpu.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/data/func_test/soc_sram_func/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files D:/data/func_test/soc_sram_func/run_vivado/soc_lite.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_lite_top -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_lite_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_lite_top_utilization_synth.rpt -pb soc_lite_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
